export const MAXXIS_AVATAR_STATES = Object.freeze({
  IDLE: 'IDLE',
  OBSERVING: 'OBSERVING',
  PROCESSING: 'PROCESSING',
  NOTICED: 'NOTICED',
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
});

export const MAXXIS_AVATAR_STATE_ORDER = Object.freeze([
  MAXXIS_AVATAR_STATES.IDLE,
  MAXXIS_AVATAR_STATES.OBSERVING,
  MAXXIS_AVATAR_STATES.NOTICED,
  MAXXIS_AVATAR_STATES.PROCESSING,
  MAXXIS_AVATAR_STATES.WAITING,
  MAXXIS_AVATAR_STATES.SUCCESS,
]);

export const MAXXIS_AVATAR_STATE_PRECEDENCE = Object.freeze({
  [MAXXIS_AVATAR_STATES.IDLE]: 0,
  [MAXXIS_AVATAR_STATES.OBSERVING]: 10,
  [MAXXIS_AVATAR_STATES.NOTICED]: 20,
  [MAXXIS_AVATAR_STATES.PROCESSING]: 30,
  [MAXXIS_AVATAR_STATES.WAITING]: 40,
  [MAXXIS_AVATAR_STATES.SUCCESS]: 50,
});

export const MAXXIS_AVATAR_ASSET_KEYS = Object.freeze({
  [MAXXIS_AVATAR_STATES.IDLE]: 'avatar-idle',
  [MAXXIS_AVATAR_STATES.OBSERVING]: 'avatar-observing',
  [MAXXIS_AVATAR_STATES.PROCESSING]: 'avatar-processing',
  [MAXXIS_AVATAR_STATES.NOTICED]: 'avatar-noticed',
  [MAXXIS_AVATAR_STATES.WAITING]: 'avatar-waiting',
  [MAXXIS_AVATAR_STATES.SUCCESS]: 'avatar-success',
});

export const MAXXIS_AVATAR_VISUAL_STATE_MODES = Object.freeze({
  NORMAL: 'normal',
  REDUCED: 'reduced',
});

export const MAXXIS_AVATAR_ANIMATION_INTENSITY = Object.freeze({
  OFF: 'OFF',
  SUBTLE: 'SUBTLE',
  NORMAL: 'NORMAL',
});

export const MAXXIS_AVATAR_TRANSIENT_MS = Object.freeze({
  [MAXXIS_AVATAR_STATES.NOTICED]: 1_500,
  [MAXXIS_AVATAR_STATES.SUCCESS]: 2_200,
});

export const MAXXIS_AVATAR_TRANSITIONS = Object.freeze({
  [MAXXIS_AVATAR_STATES.IDLE]: Object.freeze([
    MAXXIS_AVATAR_STATES.OBSERVING,
    MAXXIS_AVATAR_STATES.PROCESSING,
    MAXXIS_AVATAR_STATES.NOTICED,
    MAXXIS_AVATAR_STATES.WAITING,
    MAXXIS_AVATAR_STATES.SUCCESS,
  ]),
  [MAXXIS_AVATAR_STATES.OBSERVING]: Object.freeze([
    MAXXIS_AVATAR_STATES.IDLE,
    MAXXIS_AVATAR_STATES.PROCESSING,
    MAXXIS_AVATAR_STATES.NOTICED,
    MAXXIS_AVATAR_STATES.WAITING,
    MAXXIS_AVATAR_STATES.SUCCESS,
  ]),
  [MAXXIS_AVATAR_STATES.PROCESSING]: Object.freeze([
    MAXXIS_AVATAR_STATES.IDLE,
    MAXXIS_AVATAR_STATES.OBSERVING,
    MAXXIS_AVATAR_STATES.WAITING,
    MAXXIS_AVATAR_STATES.SUCCESS,
  ]),
  [MAXXIS_AVATAR_STATES.NOTICED]: Object.freeze([
    MAXXIS_AVATAR_STATES.IDLE,
    MAXXIS_AVATAR_STATES.OBSERVING,
    MAXXIS_AVATAR_STATES.PROCESSING,
    MAXXIS_AVATAR_STATES.WAITING,
    MAXXIS_AVATAR_STATES.SUCCESS,
  ]),
  [MAXXIS_AVATAR_STATES.WAITING]: Object.freeze([
    MAXXIS_AVATAR_STATES.IDLE,
    MAXXIS_AVATAR_STATES.OBSERVING,
    MAXXIS_AVATAR_STATES.PROCESSING,
    MAXXIS_AVATAR_STATES.SUCCESS,
  ]),
  [MAXXIS_AVATAR_STATES.SUCCESS]: Object.freeze([
    MAXXIS_AVATAR_STATES.IDLE,
    MAXXIS_AVATAR_STATES.OBSERVING,
    MAXXIS_AVATAR_STATES.PROCESSING,
    MAXXIS_AVATAR_STATES.NOTICED,
    MAXXIS_AVATAR_STATES.WAITING,
  ]),
});

export const isMaxxisAvatarState = (state) => Boolean(MAXXIS_AVATAR_STATES[String(state || '').toUpperCase()]);

