const COPY = Object.freeze({ en: Object.freeze({
  analysis_depends_on_submitted_data: 'The analysis depends partly on submitted property information that should be independently verified.',
  property_data_not_independently_verified: 'Some property information comes from submitted records and should still be independently verified.',
  arv_not_structured: 'A defensible ARV cannot be calculated with the evidence currently available.',
  ARV_EVALUATION_NOT_LOADED: 'A defensible ARV cannot be calculated with the evidence currently available.',
  roi_not_calculated: 'ROI cannot yet be calculated because one or more required investment inputs are unavailable.',
  cap_rate_not_independently_verified: 'The reported capitalization rate has not yet been independently validated.',
  MISSING_REHAB: 'Rehabilitation scope and cost have not yet been confirmed.',
  MISSING_REHAB_INFORMATION: 'Rehabilitation scope and cost have not yet been confirmed.',
  rehab_not_provided: 'Rehabilitation scope and cost have not yet been confirmed.',
  property_condition_unknown: 'The current property condition has not yet been verified.',
  INSUFFICIENT_COMPS: 'There are not enough condition-compatible recorded sales to support a defensible ARV.',
  VALUATION_DISPERSION_WARNING: 'The available comparable values vary materially, which limits valuation confidence.',
  'Target market or property location is missing.': 'Target market or property location is missing.',
  'Property location matches a target market.': 'Property location matches a target market.',
  'Property location is outside the target markets.': 'Property location is outside the target markets.',
  'The property location is outside the configured target markets.': 'The property location is outside the configured target markets.',
  'Profile price range or property price is missing.': 'Profile price range or property price is missing.',
  'Property price is inside the configured range.': 'Property price is inside the configured range.',
  'Property price is outside the configured range.': 'Property price is outside the configured range.',
  'The asking price is outside the configured Investment Profile range.': 'The asking price is outside the configured Investment Profile range.',
  'Desired type or comparable property type is missing.': 'Desired type or comparable property type is missing.',
  'Property type matches the configured profile.': 'Property type matches the configured profile.',
  'Property type does not match the configured profile.': 'Property type does not match the configured profile.',
  'Comparable strategy or property objective is missing.': 'Comparable strategy or property objective is missing.',
  'Property objective matches a configured strategy.': 'Property objective matches a configured strategy.',
  'Property objective does not match the configured strategies.': 'Property objective does not match the configured strategies.',
  'This alignment could not be evaluated from the available information.': 'This alignment could not be evaluated from the available information.',
  'Based on available evidence, profile alignment is partial.': 'Based on available evidence, profile alignment is partial.',
  'Target market aligned.': 'Target market aligned.',
  'Condition is unknown.': 'Condition is unknown.',
  'Validate condition.': 'Validate condition.',
  'Verified property records': 'Verified property records',
  'Condition unknown': 'Condition unknown',
  'Focus on potential margin and validation requirements.': 'Focus on potential margin and validation requirements.',
  'Potential spread': 'Potential spread',
  'Verification': 'Verification',
  'Based on available evidence, confidence is moderate.': 'Based on available evidence, confidence is moderate.',
  'The property has partial profile compatibility.': 'The property has partial profile compatibility.',
  'Verified records support the available characteristics.': 'Verified records support the available characteristics.',
  'Comparable evidence supports a preliminary reference.': 'Comparable evidence supports a preliminary reference.',
  'Property condition remains uncertain.': 'Property condition remains uncertain.',
  'Next verification priority: validate condition.': 'Next verification priority: validate condition.',
  'Structural dissimilarity': 'Structural dissimilarity',
  'Scenario-based illustration from existing inputs; not a return forecast or guarantee.': 'Scenario-based illustration from existing inputs; not a return forecast or guarantee.',
  'Validate property condition': 'Validate property condition',
  'Verify title and encumbrances': 'Verify title and encumbrances',
  'Inspect the comparable evidence': 'Inspect the comparable evidence',
  'Confirm all user-provided assumptions': 'Confirm all user-provided assumptions',
  'yearBuilt: UNKNOWN': 'Year built is unknown.',
}), pt: Object.freeze({
  analysis_depends_on_submitted_data: 'A análise depende parcialmente de informações cadastradas do imóvel que devem ser verificadas de forma independente.',
  property_data_not_independently_verified: 'Algumas informações do imóvel vêm de dados cadastrados e ainda precisam de verificação independente.',
  arv_not_structured: 'Não é possível calcular um ARV defensável com as evidências disponíveis.',
  ARV_EVALUATION_NOT_LOADED: 'Não é possível calcular um ARV defensável com as evidências disponíveis.',
  roi_not_calculated: 'O ROI ainda não pode ser calculado porque faltam dados essenciais do investimento.',
  cap_rate_not_independently_verified: 'A taxa de capitalização informada ainda não foi validada de forma independente.',
  MISSING_REHAB: 'O escopo e o custo da reforma ainda não foram confirmados.',
  MISSING_REHAB_INFORMATION: 'O escopo e o custo da reforma ainda não foram confirmados.',
  rehab_not_provided: 'O escopo e o custo da reforma ainda não foram confirmados.',
  property_condition_unknown: 'A condição atual do imóvel ainda não foi verificada.',
  INSUFFICIENT_COMPS: 'Não há vendas registradas compatíveis em quantidade suficiente para sustentar um ARV defensável.',
  VALUATION_DISPERSION_WARNING: 'Os valores dos comparáveis disponíveis variam de forma relevante, limitando a confiança da avaliação.',
  'Target market or property location is missing.': 'O mercado-alvo ou a localização do imóvel não foi informado.',
  'Property location matches a target market.': 'A localização do imóvel corresponde a um mercado-alvo.',
  'Property location is outside the target markets.': 'A localização do imóvel está fora dos mercados-alvo.',
  'The property location is outside the configured target markets.': 'A localização do imóvel está fora dos mercados-alvo configurados.',
  'Profile price range or property price is missing.': 'A faixa de preço do perfil ou o preço do imóvel não foi informado.',
  'Property price is inside the configured range.': 'O preço do imóvel está dentro da faixa configurada.',
  'Property price is outside the configured range.': 'O preço do imóvel está fora da faixa configurada.',
  'The asking price is outside the configured Investment Profile range.': 'O preço pedido está fora da faixa configurada no Perfil de Investimento.',
  'Desired type or comparable property type is missing.': 'O tipo de imóvel desejado ou o tipo do imóvel não foi informado.',
  'Property type matches the configured profile.': 'O tipo de imóvel corresponde ao perfil configurado.',
  'Property type does not match the configured profile.': 'O tipo de imóvel não corresponde ao perfil configurado.',
  'Comparable strategy or property objective is missing.': 'A estratégia ou o objetivo do imóvel não foi informado.',
  'Property objective matches a configured strategy.': 'O objetivo do imóvel corresponde a uma estratégia configurada.',
  'Property objective does not match the configured strategies.': 'O objetivo do imóvel não corresponde às estratégias configuradas.',
  'This alignment could not be evaluated from the available information.': 'Esta aderência não pôde ser avaliada com as informações disponíveis.',
  'Based on available evidence, profile alignment is partial.': 'Com base nas evidências disponíveis, a aderência ao perfil é parcial.',
  'Target market aligned.': 'O mercado-alvo está alinhado.',
  'Condition is unknown.': 'A condição do imóvel é desconhecida.',
  'Validate condition.': 'Valide a condição do imóvel.',
  'Verified property records': 'Registros verificados do imóvel',
  'Condition unknown': 'Condição desconhecida',
  'Focus on potential margin and validation requirements.': 'Priorize a margem potencial e os requisitos de validação.',
  'Potential spread': 'Margem potencial',
  'Verification': 'Verificação',
  'Based on available evidence, confidence is moderate.': 'Com base nas evidências disponíveis, a confiança é moderada.',
  'The property has partial profile compatibility.': 'O imóvel apresenta compatibilidade parcial com o perfil.',
  'Verified records support the available characteristics.': 'Os registros verificados sustentam as características disponíveis.',
  'Comparable evidence supports a preliminary reference.': 'As evidências comparáveis sustentam uma referência preliminar.',
  'Property condition remains uncertain.': 'A condição do imóvel ainda é incerta.',
  'Next verification priority: validate condition.': 'Próxima prioridade de verificação: validar a condição.',
  'Structural dissimilarity': 'Dissimilaridade estrutural',
  'Scenario-based illustration from existing inputs; not a return forecast or guarantee.': 'Ilustração baseada em cenários e nos dados existentes; não é previsão nem garantia de retorno.',
  'Validate property condition': 'Valide a condição do imóvel',
  'Verify title and encumbrances': 'Verifique a titularidade e eventuais ônus',
  'Inspect the comparable evidence': 'Revise as evidências dos imóveis comparáveis',
  'Confirm all user-provided assumptions': 'Confirme todas as premissas informadas pelo usuário',
  'yearBuilt: UNKNOWN': 'O ano de construção é desconhecido.',
}), es: Object.freeze({
  analysis_depends_on_submitted_data: 'El análisis depende parcialmente de información registrada de la propiedad que debe verificarse de forma independiente.',
  property_data_not_independently_verified: 'Parte de la información de la propiedad proviene de datos registrados y aún requiere verificación independiente.',
  arv_not_structured: 'No es posible calcular un ARV defendible con la evidencia disponible.',
  ARV_EVALUATION_NOT_LOADED: 'No es posible calcular un ARV defendible con la evidencia disponible.',
  roi_not_calculated: 'El ROI aún no puede calcularse porque faltan datos esenciales de la inversión.',
  cap_rate_not_independently_verified: 'La tasa de capitalización informada aún no ha sido validada de forma independiente.',
  MISSING_REHAB: 'El alcance y el costo de la reforma aún no se han confirmado.',
  MISSING_REHAB_INFORMATION: 'El alcance y el costo de la reforma aún no se han confirmado.',
  rehab_not_provided: 'El alcance y el costo de la reforma aún no se han confirmado.',
  property_condition_unknown: 'El estado actual de la propiedad aún no ha sido verificado.',
  INSUFFICIENT_COMPS: 'No hay suficientes ventas registradas compatibles para respaldar un ARV defendible.',
  VALUATION_DISPERSION_WARNING: 'Los valores de los comparables disponibles varían significativamente, lo que limita la confianza de la valoración.',
  'Target market or property location is missing.': 'Falta el mercado objetivo o la ubicación de la propiedad.',
  'Property location matches a target market.': 'La ubicación de la propiedad coincide con un mercado objetivo.',
  'Property location is outside the target markets.': 'La ubicación de la propiedad está fuera de los mercados objetivo.',
  'The property location is outside the configured target markets.': 'La ubicación de la propiedad está fuera de los mercados objetivo configurados.',
  'Profile price range or property price is missing.': 'Falta el rango de precio del perfil o el precio de la propiedad.',
  'Property price is inside the configured range.': 'El precio de la propiedad está dentro del rango configurado.',
  'Property price is outside the configured range.': 'El precio de la propiedad está fuera del rango configurado.',
  'The asking price is outside the configured Investment Profile range.': 'El precio solicitado está fuera del rango configurado en el Perfil de Inversión.',
  'Desired type or comparable property type is missing.': 'Falta el tipo de propiedad deseado o el tipo de la propiedad.',
  'Property type matches the configured profile.': 'El tipo de propiedad coincide con el perfil configurado.',
  'Property type does not match the configured profile.': 'El tipo de propiedad no coincide con el perfil configurado.',
  'Comparable strategy or property objective is missing.': 'Falta la estrategia o el objetivo de la propiedad.',
  'Property objective matches a configured strategy.': 'El objetivo de la propiedad coincide con una estrategia configurada.',
  'Property objective does not match the configured strategies.': 'El objetivo de la propiedad no coincide con las estrategias configuradas.',
  'This alignment could not be evaluated from the available information.': 'Esta afinidad no pudo evaluarse con la información disponible.',
  'Based on available evidence, profile alignment is partial.': 'Según la evidencia disponible, la afinidad con el perfil es parcial.',
  'Target market aligned.': 'El mercado objetivo está alineado.',
  'Condition is unknown.': 'Se desconoce la condición de la propiedad.',
  'Validate condition.': 'Valida la condición de la propiedad.',
  'Verified property records': 'Registros verificados de la propiedad',
  'Condition unknown': 'Condición desconocida',
  'Focus on potential margin and validation requirements.': 'Prioriza el margen potencial y los requisitos de validación.',
  'Potential spread': 'Margen potencial',
  'Verification': 'Verificación',
  'Based on available evidence, confidence is moderate.': 'Según la evidencia disponible, la confianza es moderada.',
  'The property has partial profile compatibility.': 'La propiedad tiene compatibilidad parcial con el perfil.',
  'Verified records support the available characteristics.': 'Los registros verificados respaldan las características disponibles.',
  'Comparable evidence supports a preliminary reference.': 'La evidencia comparable respalda una referencia preliminar.',
  'Property condition remains uncertain.': 'La condición de la propiedad sigue siendo incierta.',
  'Next verification priority: validate condition.': 'Próxima prioridad de verificación: validar la condición.',
  'Structural dissimilarity': 'Diferencia estructural',
  'Scenario-based illustration from existing inputs; not a return forecast or guarantee.': 'Ilustración basada en escenarios y datos existentes; no es una previsión ni garantía de retorno.',
  'Validate property condition': 'Valida la condición de la propiedad',
  'Verify title and encumbrances': 'Verifica la titularidad y los gravámenes',
  'Inspect the comparable evidence': 'Revisa la evidencia de propiedades comparables',
  'Confirm all user-provided assumptions': 'Confirma todos los supuestos proporcionados por el usuario',
  'yearBuilt: UNKNOWN': 'Se desconoce el año de construcción.',
}) });

export function explainMaxxisEvidenceState(value, language = 'en') {
  const raw = String(value ?? '').replace(/\s+/g, ' ').trim();
  const selected = ['pt', 'es'].includes(String(language).slice(0, 2)) ? String(language).slice(0, 2) : 'en';
  if (!raw) return '';
  if (COPY[selected][raw]) return COPY[selected][raw];
  const canonicalKey = Object.keys(COPY.en).find((key) => COPY.en[key] === raw);
  if (canonicalKey && COPY[selected][canonicalKey]) return COPY[selected][canonicalKey];
  if (!/^[A-Za-z0-9]+(?:_[A-Za-z0-9]+)+$/.test(raw)) return raw;
  if (selected === 'pt') return 'Há uma limitação adicional de evidência registrada para revisão.';
  if (selected === 'es') return 'Hay una limitación adicional de evidencia registrada para revisión.';
  const readable = raw.replaceAll('_', ' ').toLowerCase();
  return `${readable.charAt(0).toUpperCase()}${readable.slice(1)}.`;
}

export function explainMaxxisEvidenceList(values, limit = 12, language = 'en') {
  return [...new Set((Array.isArray(values) ? values : []).map((value) => explainMaxxisEvidenceState(value, language)).filter(Boolean))].slice(0, limit);
}
