import React, { useMemo, useState } from 'react';
import maxxisAnalysisAsset from '../../../assets/maxxis/avatar/avatar-idle.png';
import maxxisDealAsset from '../../../assets/maxxis/avatar/avatar-success.png';
import './MyMaxxisReports.css';

const COPY={en:{title:'MY MAXXIS REPORTS',all:'All',analysis:'Maxxis Analysis',deal:'Deal Intelligence',search:'Search by address',empty:'No saved reports.',view:'View',pdf:'PDF',email:'Email',remove:'Delete from history',confirm:'Remove this saved report from history? Your acquired access will remain available.',back:'Back'},pt:{title:'MEUS RELATÓRIOS MAXXIS',all:'Todos',analysis:'Análise Maxxis',deal:'Deal Intelligence',search:'Buscar por endereço',empty:'Nenhum relatório salvo.',view:'Ver',pdf:'PDF',email:'Email',remove:'Excluir do histórico',confirm:'Remover este relatório salvo do histórico? Seu acesso adquirido continuará disponível.',back:'Voltar'},es:{title:'MIS INFORMES MAXXIS',all:'Todos',analysis:'Análisis Maxxis',deal:'Deal Intelligence',search:'Buscar por dirección',empty:'No hay informes guardados.',view:'Ver',pdf:'PDF',email:'Email',remove:'Eliminar del historial',confirm:'¿Eliminar este informe guardado del historial? El acceso adquirido seguirá disponible.',back:'Volver'}};
const addressOf=r=>r?.reportPayload?.data?.maxxisReport?.sections?.propertySummary?.data?.address||r?.reportPayload?.data?.property?.address||r?.reportPayload?.address||'';

export function MyMaxxisReports({reports=[],language='en',onView,onPdf,onEmail,onDelete,onClose}){
  const t=COPY[String(language).slice(0,2)]||COPY.en;
  const[filter,setFilter]=useState('ALL');const[query,setQuery]=useState('');
  const list=useMemo(()=>reports.filter(r=>(filter==='ALL'||r.capability===filter)&&addressOf(r).toLowerCase().includes(query.toLowerCase())),[reports,filter,query]);
  return <section className="my-maxxis-reports" role="dialog" aria-label={t.title}><header><strong>{t.title}</strong><button type="button" onClick={onClose}>← {t.back}</button></header><div className="my-maxxis-report-filters">{[['ALL',t.all],['MAXXIS_ANALYSIS',t.analysis],['DEAL_INTELLIGENCE',t.deal]].map(([id,label])=><button type="button" className={filter===id?'is-active':''} onClick={()=>setFilter(id)} key={id}>{label}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><div className="my-maxxis-report-list">{list.length?list.map(r=><article key={r.id}><img src={r.capability==='DEAL_INTELLIGENCE'?maxxisDealAsset:maxxisAnalysisAsset} alt=""/><div><strong>{r.capability.replaceAll('_',' ')}</strong><span>{addressOf(r)||'Property'}</span><small>{new Date(r.createdAt).toLocaleDateString()} · {r.accessSource==='ONE_TIME_UNLOCK'?(r.capability==='MAXXIS_ANALYSIS'?'3 Nuggets':'5 Nuggets'):(r.accessSource||'Included')}</small></div><div><button type="button" onClick={()=>onView?.(r)}>{t.view}</button><button type="button" onClick={()=>onPdf?.(r)}>{t.pdf}</button><button type="button" onClick={()=>onEmail?.(r)}>{t.email}</button><button type="button" onClick={()=>{if(window.confirm(t.confirm))onDelete?.(r)}} aria-label={t.remove}>⋮</button></div></article>):<p>{t.empty}</p>}</div></section>;
}
