export const MAXXIS_EXPERIENCE_MODES = Object.freeze({
  PASSIVE: 'PASSIVE',
  CONTEXTUAL: 'CONTEXTUAL',
  ANALYSIS: 'ANALYSIS',
  CHANGE_REVIEW: 'CHANGE_REVIEW',
  PROVIDER_REVIEW: 'PROVIDER_REVIEW',
  ACTION_PREPARATION: 'ACTION_PREPARATION',
  ACTION_CONFIRMATION: 'ACTION_CONFIRMATION',
  ACTION_RESULT: 'ACTION_RESULT',
  MEMORY_RECALL: 'MEMORY_RECALL',
  WORKFLOW_REVIEW: 'WORKFLOW_REVIEW',
  COMPARISON: 'COMPARISON',
});

export const MAXXIS_EXPERIENCE_ATTENTION = Object.freeze({
  NONE: 'NONE',
  BUBBLE: 'BUBBLE',
  IN_CHAT: 'IN_CHAT',
});

export const MAXXIS_EXPERIENCE_CONTENT = Object.freeze({
  DEAL_SNAPSHOT: 'DEAL_SNAPSHOT',
  DEAL_GAP: 'DEAL_GAP',
  METRIC: 'METRIC',
  NEXT_BEST_ACTION: 'NEXT_BEST_ACTION',
  PROVIDER_REPLY: 'PROVIDER_REPLY',
  PROVIDER_QUOTE: 'PROVIDER_QUOTE',
  MEMORY_RECALL: 'MEMORY_RECALL',
  MEMORY_CHANGE: 'MEMORY_CHANGE',
  WORKFLOW: 'WORKFLOW',
  COMPARISON: 'COMPARISON',
  ACTION_PREPARATION: 'ACTION_PREPARATION',
  ACTION_CONFIRMATION: 'ACTION_CONFIRMATION',
  ACTION_RESULT: 'ACTION_RESULT',
  CONTEXT: 'CONTEXT',
});

export const MAXXIS_EXPERIENCE_REASONS = Object.freeze({
  DISABLED_SAFE: 'DISABLED_SAFE',
  ACTION_CONFIRMATION: 'ACTION_CONFIRMATION_DOMINANT',
  ACTION_PREPARATION: 'ACTION_PREPARATION_DOMINANT',
  ACTION_RESULT: 'ACTION_RESULT_DOMINANT',
  EXPLICIT_USER_INTENT: 'EXPLICIT_USER_INTENT',
  NEXT_INTERACTION_SELECTED: 'NEXT_INTERACTION_SELECTED',
  RELEVANT_CHANGE: 'RELEVANT_CHANGE',
  MEMORY_REQUESTED: 'MEMORY_REQUESTED',
  CONTEXT_AVAILABLE: 'CONTEXT_AVAILABLE',
  NO_TRUSTED_CONTENT: 'NO_TRUSTED_CONTENT',
  ATTENTION_SUPPRESSED: 'ATTENTION_SUPPRESSED',
});

export const MAXXIS_EXPERIENCE_ACTION_PHASES = Object.freeze({
  PREPARATION: 'PREPARATION',
  CONFIRMATION: 'CONFIRMATION',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
});

export const MAXXIS_EXPERIENCE_LIMITS = Object.freeze({
  SECONDARY_CONTENT: 2,
  SECONDARY_ACTIONS: 2,
});
