export const MAXXIS_COMPOSITION_DENSITIES = Object.freeze({
  COMPACT: 'COMPACT',
  STANDARD: 'STANDARD',
  DETAILED: 'DETAILED',
});

const COPY = Object.freeze({
  en: {
    modes: {
      CONTEXTUAL: 'Here is the current context.',
      ANALYSIS: 'Here is the current deal review.',
      CHANGE_REVIEW: 'Something changed.',
      PROVIDER_REVIEW: 'Your provider replied.',
      ACTION_PREPARATION: 'Your action is prepared.',
      ACTION_CONFIRMATION: 'Your confirmation is required.',
      ACTION_RESULT: 'The action is complete.',
      MEMORY_RECALL: "Here's where you left off.",
      WORKFLOW_REVIEW: 'Your workflow has an open item.',
      COMPARISON: 'Here are the current trade-offs.',
    },
    missing: (count) => count === 1 ? 'One important detail is still missing.' : `${count} important details are still missing.`,
    context: 'This is the structured context currently available.',
    metric: 'Here is the requested metric.',
    providerReady: 'The conversation is ready for review.',
    providerLocked: 'Contact details remain protected by the existing access rules.',
    prepared: 'Review it before continuing. Nothing will happen until you confirm.',
    confirm: 'Nothing will happen until you confirm.',
    unlockCost: (cost) => `Unlocking this provider will use ${cost} Nuggets.`,
    unlocked: 'Contact access is now available.',
    sent: 'The provider can now reply in this conversation.',
    success: 'The requested action completed successfully.',
    failure: 'The action did not complete. Nothing else was changed.',
    memory: 'This is the latest safe continuity context for this deal.',
    memoryChanged: (count) => count === 1 ? 'One item changed since your previous review.' : `${count} items changed since your previous review.`,
    workflow: (count) => count === 1 ? 'One workflow item is still open.' : `${count} workflow items are still open.`,
    comparison: 'The available facts show trade-offs; Maxxis Deal AI is not selecting a winner.',
    unknown: 'I do not have enough current information to compose a reliable answer.',
    actions: {
      REVIEW_PROVIDER_REPLY: 'Review reply',
      VIEW_PROVIDERS: 'Review providers',
      DRAFT_PROVIDER_MESSAGE: 'Prepare message',
      UNLOCK_PROVIDER_CONTACT: 'Review unlock',
      REVIEW_WORKFLOW: 'Continue workflow',
      REVIEW_NEXT_STEP: 'Review next step',
      VIEW_DEAL_GAPS: "What's missing?",
      EXPLAIN_INSIGHT: 'Why?',
      COMPARE_PROPERTIES: 'Review comparison',
    },
  },
  pt: {
    modes: {
      CONTEXTUAL: 'Este e o contexto atual.',
      ANALYSIS: 'Esta e a analise atual do deal.',
      CHANGE_REVIEW: 'Algo mudou.',
      PROVIDER_REVIEW: 'Seu provider respondeu.',
      ACTION_PREPARATION: 'Sua acao esta preparada.',
      ACTION_CONFIRMATION: 'Sua confirmacao e necessaria.',
      ACTION_RESULT: 'A acao foi concluida.',
      MEMORY_RECALL: 'Veja onde voce parou.',
      WORKFLOW_REVIEW: 'Seu workflow tem um item aberto.',
      COMPARISON: 'Estes sao os trade-offs atuais.',
    },
    missing: (count) => count === 1 ? 'Um dado importante ainda esta faltando.' : `${count} dados importantes ainda estao faltando.`,
    context: 'Este e o contexto estruturado disponivel agora.',
    metric: 'Esta e a metrica solicitada.',
    providerReady: 'A conversa esta pronta para revisao.',
    providerLocked: 'Os dados de contato continuam protegidos pelas regras de acesso existentes.',
    prepared: 'Revise antes de continuar. Nada acontecera ate voce confirmar.',
    confirm: 'Nada acontecera ate voce confirmar.',
    unlockCost: (cost) => `Desbloquear este provider usara ${cost} Nuggets.`,
    unlocked: 'O acesso ao contato agora esta disponivel.',
    sent: 'O provider agora pode responder nesta conversa.',
    success: 'A acao solicitada foi concluida com sucesso.',
    failure: 'A acao nao foi concluida. Nada mais foi alterado.',
    memory: 'Este e o contexto seguro mais recente deste deal.',
    memoryChanged: (count) => count === 1 ? 'Um item mudou desde sua ultima revisao.' : `${count} itens mudaram desde sua ultima revisao.`,
    workflow: (count) => count === 1 ? 'Um item do workflow continua aberto.' : `${count} itens do workflow continuam abertos.`,
    comparison: 'Os dados disponiveis mostram trade-offs; o Maxxis Deal AI nao esta escolhendo um vencedor.',
    unknown: 'Nao tenho informacoes atuais suficientes para compor uma resposta confiavel.',
    actions: {
      REVIEW_PROVIDER_REPLY: 'Revisar resposta',
      VIEW_PROVIDERS: 'Revisar providers',
      DRAFT_PROVIDER_MESSAGE: 'Preparar mensagem',
      UNLOCK_PROVIDER_CONTACT: 'Revisar desbloqueio',
      REVIEW_WORKFLOW: 'Continuar workflow',
      REVIEW_NEXT_STEP: 'Revisar proximo passo',
      VIEW_DEAL_GAPS: 'O que falta?',
      EXPLAIN_INSIGHT: 'Por que?',
      COMPARE_PROPERTIES: 'Revisar comparacao',
    },
  },
  es: {
    modes: {
      CONTEXTUAL: 'Este es el contexto actual.',
      ANALYSIS: 'Este es el analisis actual del deal.',
      CHANGE_REVIEW: 'Algo cambio.',
      PROVIDER_REVIEW: 'Tu provider respondio.',
      ACTION_PREPARATION: 'Tu accion esta preparada.',
      ACTION_CONFIRMATION: 'Tu confirmacion es necesaria.',
      ACTION_RESULT: 'La accion fue completada.',
      MEMORY_RECALL: 'Aqui es donde lo dejaste.',
      WORKFLOW_REVIEW: 'Tu workflow tiene un item abierto.',
      COMPARISON: 'Estos son los trade-offs actuales.',
    },
    missing: (count) => count === 1 ? 'Todavia falta un dato importante.' : `Todavia faltan ${count} datos importantes.`,
    context: 'Este es el contexto estructurado disponible ahora.',
    metric: 'Esta es la metrica solicitada.',
    providerReady: 'La conversacion esta lista para revision.',
    providerLocked: 'Los datos de contacto siguen protegidos por las reglas de acceso existentes.',
    prepared: 'Revisa antes de continuar. Nada ocurrira hasta que confirmes.',
    confirm: 'Nada ocurrira hasta que confirmes.',
    unlockCost: (cost) => `Desbloquear este provider usara ${cost} Nuggets.`,
    unlocked: 'El acceso al contacto ahora esta disponible.',
    sent: 'El provider ahora puede responder en esta conversacion.',
    success: 'La accion solicitada se completo correctamente.',
    failure: 'La accion no se completo. Nada mas fue modificado.',
    memory: 'Este es el contexto seguro mas reciente de este deal.',
    memoryChanged: (count) => count === 1 ? 'Un item cambio desde tu ultima revision.' : `${count} items cambiaron desde tu ultima revision.`,
    workflow: (count) => count === 1 ? 'Un item del workflow sigue abierto.' : `${count} items del workflow siguen abiertos.`,
    comparison: 'Los datos disponibles muestran trade-offs; Maxxis Deal AI no esta eligiendo un ganador.',
    unknown: 'No tengo suficiente informacion actual para componer una respuesta confiable.',
    actions: {
      REVIEW_PROVIDER_REPLY: 'Revisar respuesta',
      VIEW_PROVIDERS: 'Revisar providers',
      DRAFT_PROVIDER_MESSAGE: 'Preparar mensaje',
      UNLOCK_PROVIDER_CONTACT: 'Revisar desbloqueo',
      REVIEW_WORKFLOW: 'Continuar workflow',
      REVIEW_NEXT_STEP: 'Revisar siguiente paso',
      VIEW_DEAL_GAPS: 'Que falta?',
      EXPLAIN_INSIGHT: 'Por que?',
      COMPARE_PROPERTIES: 'Revisar comparacion',
    },
  },
});

export function getMaxxisExperienceCopy(language = 'en') {
  return COPY[language] || COPY.en;
}
