export const MAXXIS_NEXT_INTERACTION_TYPES = Object.freeze({
  PASSIVE: 'PASSIVE',
  REVIEW_CHANGE: 'REVIEW_CHANGE',
  REVIEW_PROVIDER_REPLY: 'REVIEW_PROVIDER_REPLY',
  REVIEW_DEAL_GAP: 'REVIEW_DEAL_GAP',
  REVIEW_PENDING_ACTION: 'REVIEW_PENDING_ACTION',
  CONTINUE_WORKFLOW: 'CONTINUE_WORKFLOW',
  REVIEW_PROVIDERS: 'REVIEW_PROVIDERS',
  PREPARE_MESSAGE: 'PREPARE_MESSAGE',
  REVIEW_UNLOCK: 'REVIEW_UNLOCK',
  EXPLAIN_METRIC: 'EXPLAIN_METRIC',
  RESUME_CONTEXT: 'RESUME_CONTEXT',
  REVIEW_COMPARISON: 'REVIEW_COMPARISON',
});

export const MAXXIS_NEXT_INTERACTION_REASONS = Object.freeze({
  USER_REQUESTED: 'USER_REQUESTED',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  MEANINGFUL_CHANGE: 'MEANINGFUL_CHANGE',
  NEW_PROVIDER_REPLY: 'NEW_PROVIDER_REPLY',
  PENDING_ACTION_EXPIRING: 'PENDING_ACTION_EXPIRING',
  IMPORTANT_GAP: 'IMPORTANT_GAP',
  WORKFLOW_OPEN: 'WORKFLOW_OPEN',
  PROVIDER_HELP_AVAILABLE: 'PROVIDER_HELP_AVAILABLE',
  METRIC_EXPLANATION_AVAILABLE: 'METRIC_EXPLANATION_AVAILABLE',
  MEMORY_CONTINUATION: 'MEMORY_CONTINUATION',
  NO_ACTIONABLE_CHANGE: 'NO_ACTIONABLE_CHANGE',
  PROPERTY_UNAVAILABLE: 'PROPERTY_UNAVAILABLE',
});

export const MAXXIS_NEXT_INTERACTION_CONFIDENCE = Object.freeze({
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
});

export const MAXXIS_NEXT_INTERACTION_PRIORITY = Object.freeze({
  EXPLICIT_INTENT: 1000,
  PENDING_CONFIRMATION: 900,
  MEANINGFUL_CHANGE: 800,
  PROVIDER_REPLY: 780,
  EXPIRING_ACTION: 740,
  IMPORTANT_GAP: 680,
  WORKFLOW: 600,
  PROVIDER_HELP: 520,
  METRIC_EXPLANATION: 440,
  MEMORY: 320,
  PASSIVE: 0,
});

export const MAXXIS_NEXT_ACTION_TO_INTERACTION = Object.freeze({
  VIEW_DEAL_GAPS: MAXXIS_NEXT_INTERACTION_TYPES.REVIEW_DEAL_GAP,
  EXPLAIN_INSIGHT: MAXXIS_NEXT_INTERACTION_TYPES.EXPLAIN_METRIC,
  VIEW_PROVIDERS: MAXXIS_NEXT_INTERACTION_TYPES.REVIEW_PROVIDERS,
  UNLOCK_PROVIDER_CONTACT: MAXXIS_NEXT_INTERACTION_TYPES.REVIEW_UNLOCK,
  DRAFT_PROVIDER_MESSAGE: MAXXIS_NEXT_INTERACTION_TYPES.PREPARE_MESSAGE,
  REVIEW_PROVIDER_REPLY: MAXXIS_NEXT_INTERACTION_TYPES.REVIEW_PROVIDER_REPLY,
  DRAFT_PROVIDER_REPLY: MAXXIS_NEXT_INTERACTION_TYPES.PREPARE_MESSAGE,
  COMPARE_PROPERTIES: MAXXIS_NEXT_INTERACTION_TYPES.REVIEW_COMPARISON,
  REVIEW_WORKFLOW: MAXXIS_NEXT_INTERACTION_TYPES.CONTINUE_WORKFLOW,
  REVIEW_NEXT_STEP: MAXXIS_NEXT_INTERACTION_TYPES.CONTINUE_WORKFLOW,
});
